### ISSUE TITLE
是否有更新版本的glossary.dat ？

### ISSUE THREAD

**Issue by yaleimeng** [liuquncn/WordSimilarity#1]
项目中所用hownet数据仍为2000年版本（66181行）。不知道现在是否有新版中文词表数据可用？

**Comment by liuquncn** [comment]
Hownet后来的版本好像都是收费的，可以登录hownet网站www.keenage.com了解详情。

**Comment by yaleimeng** [comment]
嗯。我看了官网介绍，似乎确实只对购买了该产品的的客户进行更新。经过几次大的更新，词汇量估计突破10万了，但只能被少数机构使用，还是比较遗憾的。
